apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: project-files
          persistentVolumeClaim:
            claimName: project-pvc
      containers:
        - name: todo-app
          image: davidsboteron/todo-app:4
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: project-files
              mountPath: /usr/src/app/files
