apiVersion: v1
kind: Secret
metadata:
  name: todo-postgres-secret
  namespace: project
type: Opaque
data:
  POSTGRES_PASSWORD: cHJvamVjdC1leGFtcGxl
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwcm9qZWN0LWV4YW1wbGVAdG9kby1wb3N0Z3Jlcy1zdmM6NTQzMi9wb3N0Z3Jlcw==
