apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ping-pong-hc
  namespace: exercises
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 3000
        requestPath: /pongs
  targetRef:
    group: ""
    kind: Service
    name: ping-pong-svc
