apiVersion: v1
kind: Service
metadata:
  name: pingpong-postgres-svc
  namespace: exercises
  labels:
    app: pingpong-postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: pingpong-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingpong-postgres-ss
  namespace: exercises
spec:
  serviceName: pingpong-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-postgres
  template:
    metadata:
      labels:
        app: pingpong-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.0
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "pingpong-example"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
