apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - manifests/todo-app-pvc.yaml
  - manifests/todo-postgres-secret.yaml
  - manifests/todo-postgres.yaml
  - manifests/todo-backend-deployment.yaml
  - manifests/todo-backend-service.yaml
  - manifests/todo-app-deployment.yaml
  - manifests/todo-app-service.yaml
  - manifests/todo-app-ingress.yaml
  - manifests/todo-cronjob.yaml
images:
  - name: PROJECT/TODO_APP
    newName: davidsboteron/todo-app
    newTag: "6"
  - name: PROJECT/TODO_BACKEND
    newName: davidbotero/todo-backend
    newTag: "5"
  - name: PROJECT/TODO_CRON
    newName: davidsboteron/todo-cron
    newTag: "2"
