apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-status
          emptyDir: {}
        - name: shared-pongs
          persistentVolumeClaim:
            claimName: pingpong-log-pvc
      containers:
        - name: log-writer
          image: davidsboteron/log-writer:1
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/files
        - name: log-reader
          image: davidsboteron/log-reader:2
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/files
            - name: shared-pongs
              mountPath: /usr/src/app/pongfiles
              readOnly: true
