apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/gateway.yaml
- manifests/route.yaml
images:
- name: PROJECT/LOG_READER
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/log-reader
  newTag: dd8e62296ecbe749f5e997e118d1689cac6f510d
- name: PROJECT/LOG_WRITER
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/log-writer
  newTag: dd8e62296ecbe749f5e997e118d1689cac6f510d
