apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/waypoint.yaml
- manifests/greeter.yaml
images:
- name: PROJECT/LOG_READER
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/log-reader
  newTag: ec0f4ef8e1123ef980e55f928f2904941e8d0b30
- name: PROJECT/LOG_WRITER
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/log-writer
  newTag: ec0f4ef8e1123ef980e55f928f2904941e8d0b30
