apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/waypoint.yaml
- manifests/greeter.yaml
images:
- name: PROJECT/LOG_READER
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/log-reader
  newTag: 1dc90ac79a43d2d9715311a25f9b126d6afc3a60
- name: PROJECT/LOG_WRITER
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/log-writer
  newTag: 1dc90ac79a43d2d9715311a25f9b126d6afc3a60
