name: Release application

on:
  push:
    branches:
      - main
    paths:
      - "the_project/**"
      - ".github/workflows/main.yaml"

permissions:
  contents: write
  id-token: write

concurrency:
  group: release
  cancel-in-progress: false

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: dwk-repository

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    environment: GKE_PROJECT

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker for Artifact Registry
        run: gcloud --quiet auth configure-docker $REGISTRY

      # tag the images with the commit SHA to get a unique tag
      - name: Build and publish images
        run: |
          for app in todo-app todo-backend todo-cron broadcaster; do
            image="$REGISTRY/$PROJECT_ID/$REPOSITORY/$app:$GITHUB_SHA"
            docker build --tag "$image" "the_project/$app"
            docker push "$image"
          done

      - name: Use the new images
        working-directory: the_project
        run: |-
          kustomize edit set image \
            PROJECT/TODO_APP=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-app:$GITHUB_SHA \
            PROJECT/TODO_BACKEND=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:$GITHUB_SHA \
            PROJECT/TODO_CRON=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-cron:$GITHUB_SHA \
            PROJECT/BROADCASTER=$REGISTRY/$PROJECT_ID/$REPOSITORY/broadcaster:$GITHUB_SHA

      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v10
        with:
          add: the_project/kustomization.yaml
          message: New project version released ${{ github.sha }}
